### ISSUE TITLE
 It is good practice to use destructuring.

### ISSUE THREAD

**Issue by FranFara** [arcejuanma/rickmortychallenge#2]
https://github.com/arcejuanma/rickmortychallenge/blob/d1f3bda59f7bb12bfc4b77641aa250f706d46ba6/src/components/FilterCategory/FilterCategory.tsx#L8

It is good practice to use destructuring. In this case you could do the following:

const {entity, title, values} = props;

And after that, you could use the variables without props.

**Comment by arcejuanma** [comment]
Done! Thanks!!
